version: '3'

tasks:
  default:
    cmds:
      - task: build

  build:
    env:
      CGO_ENABLED: 1
      CGO_LDFLAGS: -L/opt/homebrew/Cellar/duckdb/1.3.0/lib
    cmds:
      - go build -tags=duckdb_use_lib -o gofd .
